require 'spec_helper'

feature 'Forwarding labels', js: true do
  include AutocompleteSteps
  include MailForwardingSteps

  def create_forwarding_recipient(attributes)
    user = create(
      :user,
      :forwarding_account,
      first_name: attributes.delete(:first_name),
      last_name: attributes.delete(:last_name)
    )

    create(:forwarding_address, attributes.merge(user: user))

    user
  end

  let!(:crufty) do
    create_forwarding_recipient(
      first_name: 'Crufty',
      last_name: 'Alumni',
      street: '123 Beacon St',
      city: 'Boston',
      state: 'MA',
      country: 'US',
      postal_code: '02140'
    )
  end

  let!(:bob) do
    create_forwarding_recipient(
      first_name: 'Bob',
      last_name: 'Chafe',
      street: '77 Mass Ave',
      city: 'Cambridge',
      state: 'MA',
      country: 'US',
      postal_code: '02139'
    )
  end

  let!(:dave) do
    create_forwarding_recipient(
      first_name: 'Dave',
      last_name: 'Student',
      street: '77 Mass Ave',
      city: 'Cambridge',
      state: 'MA',
      country: 'US',
      postal_code: '02139'
    )
  end

  scenario 'are generated by adding recipients and changing the number of labels to print' do
    sign_in create(:user, :mail_forwarder)

    click_link 'Mail Forwarding'

    current_path.should eq forwarding_path

    page.should_not have_button 'Generate Labels'

    # Add users
    within recipient_search do
      fill_in 'Name', with: 'crufty'
      autocomplete_result('Crufty Alumni').click

      fill_in 'Name', with: 'bob'
      autocomplete_result('Bob Chafe').click

      fill_in 'Name', with: 'dave'
      autocomplete_result('Dave Student').click
    end

    # Manually adjust how many labels to print
    within user_element(text: 'Crufty Alumni') do
      find('input[type=number]').set('3')
    end

    within user_element(text: 'Bob Chafe') do
      find('input[type=number]').set('2')
    end

    # Remove a user
    within user_element(text: 'Dave Student') do
      click_button 'Remove'
    end

    # Increment count by adding a user again
    within recipient_search do
      fill_in 'Name', with: 'crufty'
      autocomplete_result('Crufty Alumni').click
    end

    click_button 'Generate Labels'

    # Ensure the table and search are removed
    page.should_not have_autocomplete_input
    page.should_not have_user_element

    # Verify the right number of labels are presented
    within forwarding_labels_collection do
      page.should have_forwarding_label_element count: 4, text: 'Crufty Alumni'

      within forwarding_label_element(text: 'Crufty Alumni', match: :first) do
        page.should have_content '123 Beacon St'
        page.should have_content 'Boston, MA 02140'
      end

      page.should have_forwarding_label_element count: 2, text: 'Bob Chafe'

      within forwarding_label_element(text: 'Bob Chafe', match: :first) do
        page.should have_content '77 Mass Ave'
        page.should have_content 'Cambridge, MA 02139'
      end

      page.should_not have_forwarding_label_element text: 'Dave Student'
    end

    # Check that we can go back to the table
    click_link 'Cancel'

    page.should have_user_element count: 2

    # Ensure we can clear out the added users.
    click_link 'Clear'

    page.should_not have_user_element
  end

  scenario 'remembers state' do
    sign_in create(:user, :mail_forwarder)

    visit forwarding_path

    within recipient_search do
      fill_in 'Name', with: 'crufty'
      autocomplete_result('Crufty Alumni').click
    end

    within recipient_search do
      fill_in 'Name', with: 'dave'
      autocomplete_result('Dave Student').click
    end

    within user_element(text: 'Dave Student') do
      find('input[type=number]').set('2')
    end

    visit forwarding_path

    page.should have_user_element text: 'Crufty Alumni'
    page.should have_user_element text: 'Dave Student'
    'Crufty Alumni'.should appear_before 'Dave Student'

    within user_element(text: 'Dave Student') do
      find('input[type=number]')['value'].should eq '2'
    end

    click_button 'Generate Labels'
    visit forwarding_path

    page.should_not have_user_element
    page.should have_forwarding_label_element count: 3
    page.should have_forwarding_label_element count: 2, text: 'Dave Student'

    click_link 'Cancel'
    visit forwarding_path

    page.should have_user_element count: 2
    page.should_not have_forwarding_label_element

    within user_element(text: 'Crufty Alumni') do
      click_button 'Remove'
    end
    visit forwarding_path

    page.should_not have_user_element text: 'Crufty Alumni'
    page.should have_user_element text: 'Dave Student'

    click_link 'Clear'
    visit forwarding_path

    page.should_not have_user_element text: 'Crufty Alumni'
    page.should_not have_user_element text: 'Dave Student'
  end

  scenario 'is only accessible to people authorized to forward mail' do
    sign_in create(:user)

    page.should_not have_link 'Mail Forwarding'
    visit forwarding_path
    current_path.should eq root_path

    sign_out!

    sign_in create(:user, :mail_forwarder)

    click_link 'Mail Forwarding'
    current_path.should eq forwarding_path
  end
end
