development:
  adapter: mysql2
  database: besker_development
  username: edd_d
  host: localhost
  encoding: utf8
  
test: &test
  adapter: mysql2
  database: besker_test
  username: edd_d
  host: localhost
  encoding: utf8

cucumber:
  <<: *test