development:
  adapter: postgresql
  database: besko
  host: localhost
  encoding: utf8
  pool: 30

test:
  adapter: postgresql
  database: besko_test
  host: localhost
  encoding: utf8
  <% if ENV['TRAVIS'] %>
  username: travis
  <% end %>
