defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>

development:
  <<: *defaults
  database: besko

test:
  <<: *defaults
  database: besko_test

production:
  <<: *defaults
  url: <%= ENV["DATABASE_URL"] %>
